### ISSUE TITLE
Problem with getting GTM pool information with new F5 version

### ISSUE THREAD

**Issue by aaronmurraywork** [F5Networks/f5-common-python#1404]
I am having a problem with code that was working against a GTM in version 11.6.0 that can not get the information now in version 12.1.2.  

pool_obj = mgmt.tm.gtm.pools.pool.load(partition='Common', name=gtm_pool['Pool_Name'])

This is the piece of code I am running and a example value of the 'Pool_Name' variable is 'OTCWebPool1'  in f5 version 11.6.0 it ran just fine but when I upgraded to 12.1.2 on my GTMs I get the following error:

 File "C:\Program Files (x86)\Python36-32\lib\site-packages\f5\bigip\mixins.py", line 102, in __getattr__ raise AttributeError(error_message)
AttributeError: '<class 'f5.bigip.tm.gtm.pool.PoolOrganizingCollection'>' object has no attribute 'pool'

I have done a lot of searching on this issue and am unable to solve it.  I am running version 3.0.11 of the F5 sdk.

Thanks.

**Comment by caphrim007** [comment]
@aaronmurraywork in version 12.0.0 of BIG-IP, the APIs for this changed to require a "type" of pool to query for. Unfortunately, this was a breaking change in the API.

To get the information you want, include the type of the pool in your API call.

For example,

```
AAAA pool
pool_obj = mgmt.tm.gtm.pools.aaaas.pool.load(partition='Common', name=gtm_pool['Pool_Name'])

A pool
pool_obj = mgmt.tm.gtm.pools.a_s.pool.load(partition='Common', name=gtm_pool['Pool_Name'])

MX pool
pool_obj = mgmt.tm.gtm.pools.mxs.pool.load(partition='Common', name=gtm_pool['Pool_Name'])
```

**Comment by aaronmurraywork** [comment]
Thank you for your response it helped me find the right answer.  The actual needed was below.  I needed to replace the word 'pool' with the 'a' as well.


pool_obj = mgmt.tm.gtm.pools.a_s.a.load(partition='Common', name=gtm_pool['Pool_Name'])


Thanks.

**Comment by vvoody** [comment]
### Wide IP
```
# 11.5
wideip = mgmt.tm.gtm.wideips.wideip.load(name='xxx.foobar.com')
# 12.0+
a_wideip = mgmt.tm.gtm.wideips.a_s.a.load(name='test-a.foobar.com')
aaaa_wideip = mgmt.tm.gtm.wideips.aaaas.aaaa.load(name='test-aaaa.foobar.com')
cname_wideip = mgmt.tm.gtm.wideips.cnames.cname.load(name='test-cname.foobar.com')
```

### Pool
```
# 11.5
pool = mgmt.tm.gtm.pools.pool.load(name='foobar_pool')
# 12.0+
a_pool = mgmt.tm.gtm.pools.a_s.a.load(name='a_foobar_pool')
aaaa_pool = mgmt.tm.gtm.pools.aaaas.aaaa.load(name='aaaa_foobar_pool')
cname_pool = mgmt.tm.gtm.pools.cnames.cname.load(name='cname_foobar_pool')
```
